#!/bin/bash
#Author:Allen
#Descripttion:Collect server information
#company:canway

################################################################
export LANG="en_US.UTF-8"
################################################################


#主机名称
hostname=`hostname`
echo "hostname=${hostname}"

#操作系统版本
rhel=`cat /etc/redhat-release |sed  "s/Red Hat Enterprise Linux Server release/RHEL/g" |awk -F. '{print $1}'`
centos=`cat /etc/redhat-release |grep CentOS |awk '{print $1,$3}' |awk -F. '{print $1}'`
[ -n "$rhel" ] && echo "operating_system=${rhel}"
[ -n "$centos" ] && echo "operating_system=${centos}"
exit 0
